evaluation:
  model: A   # o B
data:
  matchup: data/matchup.csv
  target: DOCmindepth_0to50

  train_idx_a: data/train_idx_ANNa.csv
  val_idx_a: data/val_idx_ANNa.csv

  train_idx_b: data/train_idx_ANNb.csv
  val_idx_b: data/val_idx_ANNb.csv

model:
  A_path: models/DOCANNa.h5
  B_path: models/DOCANNb.h5

  A_scaler: models/DOCANNa_scaler.pkl
  B_scaler: models/DOCANNb_scaler.pkl

  A_predictors:
    - CHL_OC4_2
    - SST_table_2
    - cdom443_BL1_3
    - MLD_table_2

  B_predictors:
    - SST_table_2
    - cdom443_BL1_3
    - MLD_table_2
